// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using User.Infrastructure.Persistence;

#nullable disable

namespace User.Infrastructure.Migrations
{
    [DbContext(typeof(UsersContext))]
    partial class UsersContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("User.Domain.Entities.Profile", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Profiles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("11111111-1111-1111-1111-111111111111"),
                            AvatarUrl = "https://i.pravatar.cc/150?u=alice@dashboard.local",
                            CreatedUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Engineering",
                            Email = "alice@dashboard.local",
                            FirstName = "Alice",
                            IsActive = true,
                            LastName = "Walker"
                        },
                        new
                        {
                            UserId = new Guid("22222222-2222-2222-2222-222222222222"),
                            AvatarUrl = "https://i.pravatar.cc/150?u=bob@dashboard.local",
                            CreatedUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Engineering",
                            Email = "bob@dashboard.local",
                            FirstName = "Bob",
                            IsActive = true,
                            LastName = "Stone"
                        },
                        new
                        {
                            UserId = new Guid("33333333-3333-3333-3333-333333333333"),
                            AvatarUrl = "https://i.pravatar.cc/150?u=carol@dashboard.local",
                            CreatedUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "QA",
                            Email = "carol@dashboard.local",
                            FirstName = "Carol",
                            IsActive = true,
                            LastName = "Nguyen"
                        },
                        new
                        {
                            UserId = new Guid("44444444-4444-4444-4444-444444444444"),
                            AvatarUrl = "https://i.pravatar.cc/150?u=dave@dashboard.local",
                            CreatedUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "QA",
                            Email = "dave@dashboard.local",
                            FirstName = "Dave",
                            IsActive = true,
                            LastName = "Patel"
                        },
                        new
                        {
                            UserId = new Guid("55555555-5555-5555-5555-555555555555"),
                            AvatarUrl = "https://i.pravatar.cc/150?u=erin@dashboard.local",
                            CreatedUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Product",
                            Email = "erin@dashboard.local",
                            FirstName = "Erin",
                            IsActive = true,
                            LastName = "Lopez"
                        },
                        new
                        {
                            UserId = new Guid("66666666-6666-6666-6666-666666666666"),
                            AvatarUrl = "https://i.pravatar.cc/150?u=frank@dashboard.local",
                            CreatedUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Product",
                            Email = "frank@dashboard.local",
                            FirstName = "Frank",
                            IsActive = true,
                            LastName = "Murphy"
                        },
                        new
                        {
                            UserId = new Guid("77777777-7777-7777-7777-777777777777"),
                            AvatarUrl = "https://i.pravatar.cc/150?u=grace@dashboard.local",
                            CreatedUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Engineering",
                            Email = "grace@dashboard.local",
                            FirstName = "Grace",
                            IsActive = true,
                            LastName = "Kim"
                        },
                        new
                        {
                            UserId = new Guid("88888888-8888-8888-8888-888888888888"),
                            AvatarUrl = "https://i.pravatar.cc/150?u=henry@dashboard.local",
                            CreatedUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Engineering",
                            Email = "henry@dashboard.local",
                            FirstName = "Henry",
                            IsActive = true,
                            LastName = "Adams"
                        },
                        new
                        {
                            UserId = new Guid("99999999-9999-9999-9999-999999999999"),
                            AvatarUrl = "https://i.pravatar.cc/150?u=irene@dashboard.local",
                            CreatedUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Engineering",
                            Email = "irene@dashboard.local",
                            FirstName = "Irene",
                            IsActive = true,
                            LastName = "Costa"
                        },
                        new
                        {
                            UserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            AvatarUrl = "https://i.pravatar.cc/150?u=jack@dashboard.local",
                            CreatedUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "QA",
                            Email = "jack@dashboard.local",
                            FirstName = "Jack",
                            IsActive = true,
                            LastName = "Owens"
                        });
                });

            modelBuilder.Entity("User.Domain.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Role")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("UserId", "Role");

                    b.ToTable("UserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Role = "Dev"
                        },
                        new
                        {
                            UserId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Role = "Dev"
                        },
                        new
                        {
                            UserId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Role = "QA"
                        },
                        new
                        {
                            UserId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Role = "QA"
                        },
                        new
                        {
                            UserId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Role = "Dev"
                        },
                        new
                        {
                            UserId = new Guid("55555555-5555-5555-5555-555555555555"),
                            Role = "PO"
                        },
                        new
                        {
                            UserId = new Guid("66666666-6666-6666-6666-666666666666"),
                            Role = "PO"
                        },
                        new
                        {
                            UserId = new Guid("77777777-7777-7777-7777-777777777777"),
                            Role = "Lead"
                        },
                        new
                        {
                            UserId = new Guid("88888888-8888-8888-8888-888888888888"),
                            Role = "Dev"
                        },
                        new
                        {
                            UserId = new Guid("88888888-8888-8888-8888-888888888888"),
                            Role = "Lead"
                        },
                        new
                        {
                            UserId = new Guid("99999999-9999-9999-9999-999999999999"),
                            Role = "Dev"
                        },
                        new
                        {
                            UserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Role = "QA"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
